package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AssignmentTest {

    @Test
    void testAssignmentConstructor_autoGeneratedId() {
        Assignment assignment = new Assignment("Assignment 1", 50.0);
        boolean expResult = true;
        boolean result = assignment.getAssignmentId().startsWith("A");
        assertEquals(expResult, result);
        assertNotNull(assignment.getAssignmentId());
    }

    @Test
    void testAssignmentConstructor_emptyScores() {
        Assignment assignment = new Assignment("Assignment 1", 50.0);
        int expSize = 0;
        int result = assignment.getScores().size();
        assertEquals(expSize, result);
    }

    @Test
    void testCalcAssignmentAvg_emptyScores() {
        Assignment assignment = new Assignment("Assignment 1", 50.0);
        double expResult = 0.0;
        double result = assignment.calcAssignmentAvg();
        assertEquals(expResult, result);
    }

    @Test
    void testCalcAssignmentAvg_validScores() {
        Assignment assignment = new Assignment("Assignment 1", 50.0);
        assignment.getScores().add(80);
        assignment.getScores().add(90);
        assignment.getScores().add(70);
        double expResult = 80.0;
        double result = assignment.calcAssignmentAvg();
        assertEquals(expResult, result, 0.01);
    }

    @Test
    void testCalcAssignmentAvg_ignoresNull() {
        Assignment assignment = new Assignment("Assignment 1", 50.0);
        assignment.getScores().add(80);
        assignment.getScores().add(null);
        assignment.getScores().add(90);
        double expResult = 85.0;
        double result = assignment.calcAssignmentAvg();
        assertEquals(expResult, result, 0.01);
    }

    @Test
    void testCalcAssignmentAvg_allNull() {
        Assignment assignment = new Assignment("Assignment 1", 50.0);
        assignment.getScores().add(null);
        assignment.getScores().add(null);
        double expResult = 0.0;
        double result = assignment.calcAssignmentAvg();
        assertEquals(expResult, result);
    }

    @Test
    void testGenerateRandomScore_generatesScores() {
        Assignment assignment = new Assignment("Assignment 1", 50.0);
        assignment.getScores().add(null);
        assignment.getScores().add(null);
        assignment.generateRandomScore();
        assertNotNull(assignment.getScores().get(0));
        assertNotNull(assignment.getScores().get(1));
    }

    @Test
    void testGenerateRandomScore_validRange() {
        Assignment assignment = new Assignment("Assignment 1", 50.0);
        assignment.getScores().add(null);
        assignment.generateRandomScore();
        int score = assignment.getScores().get(0);
        assertTrue(score >= 0 && score <= 100);
    }

    @Test
    void testToString() {
        Assignment assignment = new Assignment("Assignment 1", 50.0);
        String result = assignment.toString();
        assertTrue(result.contains(assignment.getAssignmentId()));
        assertTrue(result.contains("Assignment 1"));
        assertTrue(result.contains("50.0"));
    }
}
