package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class CourseTest {

    @Test
    void testCourseConstructor_autoGeneratedId() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        boolean expResult = true;
        boolean result = course.getCourseId().startsWith("C-");
        assertEquals(expResult, result);
        assertNotNull(course.getCourseId());
    }

    @Test
    void testCourseConstructor_titleCase() {
        Department department = new Department("Computer Science");
        Course course = new Course("programming 1", 3.0, department);
        String expCourseName = "Programming 1";
        String result = course.getCourseName();
        assertEquals(expCourseName, result);
    }

    @Test
    void testCourseConstructor_emptyLists() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        int expSize = 0;
        int resultAssignments = course.getAssignments().size();
        int resultStudents = course.getRegisteredStudents().size();
        int resultFinalScores = course.getFinalScores().size();
        assertEquals(expSize, resultAssignments);
        assertEquals(expSize, resultStudents);
        assertEquals(expSize, resultFinalScores);
    }

    @Test
    void testIsAssignmentWeightValid_sumEquals100() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        course.addAssignment("Assignment 1", 50.0, 100);
        course.addAssignment("Assignment 2", 30.0, 100);
        course.addAssignment("Exam", 20.0, 100);
        boolean expResult = true;
        boolean result = course.isAssignmentWeightValid();
        assertEquals(expResult, result);
    }

    @Test
    void testIsAssignmentWeightValid_sumNot100() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        course.addAssignment("Assignment 1", 50.0, 100);
        course.addAssignment("Assignment 2", 30.0, 100);
        boolean expResult = false;
        boolean result = course.isAssignmentWeightValid();
        assertEquals(expResult, result);
    }

    @Test
    void testIsAssignmentWeightValid_emptyAssignments() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        boolean expResult = false;
        boolean result = course.isAssignmentWeightValid();
        assertEquals(expResult, result);
    }

    @Test
    void testRegisterStudent_success() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        boolean expResult = true;
        boolean result = course.registerStudent(student);
        assertEquals(expResult, result);
        assertTrue(course.getRegisteredStudents().contains(student));
    }

    @Test
    void testRegisterStudent_alreadyRegistered() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        course.registerStudent(student);
        boolean expResult = false;
        boolean result = course.registerStudent(student);
        assertEquals(expResult, result);
    }

    @Test
    void testCalcStudentsAverage_noStudents() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        int expLength = 0;
        int[] result = course.calcStudentsAverage();
        assertEquals(expLength, result.length);
    }

    @Test
    void testCalcStudentsAverage_valid() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        course.addAssignment("Assignment 1", 50.0, 100);
        course.addAssignment("Assignment 2", 50.0, 100);
        course.registerStudent(student);
        course.getAssignments().get(0).getScores().set(0, 80);
        course.getAssignments().get(1).getScores().set(0, 90);
        int[] result = course.calcStudentsAverage();
        int expResult = 85;
        assertEquals(expResult, result[0]);
    }

    @Test
    void testAddAssignment_success() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        boolean expResult = true;
        boolean result = course.addAssignment("Assignment 1", 50.0, 100);
        assertEquals(expResult, result);
        assertEquals(1, course.getAssignments().size());
    }

    @Test
    void testGenerateScores() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        course.addAssignment("Assignment 1", 50.0, 100);
        course.registerStudent(student);
        course.generateScores();
        assertNotNull(course.getAssignments().get(0).getScores().get(0));
        assertNotNull(course.getFinalScores().get(0));
    }

    @Test
    void testToSimplifiedString() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        String result = course.toSimplifiedString();
        assertTrue(result.contains(course.getCourseId()));
        assertTrue(result.contains("Programming 1"));
        assertTrue(result.contains("3.0"));
    }

    @Test
    void testToString() {
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        String result = course.toString();
        assertTrue(result.contains(course.getCourseId()));
        assertTrue(result.contains("Programming 1"));
        assertTrue(result.contains("isAssignmentWeightValid"));
    }
}
