package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class StudentTest {

    @Test
    void testStudentConstructor_autoGeneratedId() {
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Department department = new Department("Computer Science");
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        boolean expResult = true;
        boolean result = student.getStudentId().startsWith("S");
        assertEquals(expResult, result);
        assertNotNull(student.getStudentId());
    }

    @Test
    void testStudentConstructor_titleCase() {
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Department department = new Department("Computer Science");
        Student student = new Student("john doe", Student.Gender.MALE, address, department);
        String expStudentName = "John Doe";
        String result = student.getStudentName();
        assertEquals(expStudentName, result);
    }

    @Test
    void testStudentConstructor_emptyCourses() {
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Department department = new Department("Computer Science");
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        int expSize = 0;
        int result = student.getRegisteredCourses().size();
        assertEquals(expSize, result);
    }

    @Test
    void testRegisterCourse_success() {
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        boolean expResult = true;
        boolean result = student.registerCourse(course);
        assertEquals(expResult, result);
        assertTrue(student.getRegisteredCourses().contains(course));
    }

    @Test
    void testRegisterCourse_alreadyRegistered() {
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        student.registerCourse(course);
        boolean expResult = false;
        boolean result = student.registerCourse(course);
        assertEquals(expResult, result);
    }

    @Test
    void testDropCourse_success() {
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        student.registerCourse(course);
        boolean expResult = true;
        boolean result = student.dropCourse(course);
        assertEquals(expResult, result);
        assertFalse(student.getRegisteredCourses().contains(course));
    }

    @Test
    void testDropCourse_notRegistered() {
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        boolean expResult = false;
        boolean result = student.dropCourse(course);
        assertEquals(expResult, result);
    }

    @Test
    void testToSimplifiedString() {
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Department department = new Department("Computer Science");
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        String result = student.toSimplifiedString();
        assertTrue(result.contains(student.getStudentId()));
        assertTrue(result.contains("John Doe"));
        assertTrue(result.contains(department.getDepartmentName()));
    }

    @Test
    void testToString() {
        Address address = new Address(123, "Main St", "Toronto", Address.Province.ON, "M5H2N2");
        Department department = new Department("Computer Science");
        Course course = new Course("Programming 1", 3.0, department);
        Student student = new Student("John Doe", Student.Gender.MALE, address, department);
        student.registerCourse(course);
        String result = student.toString();
        assertTrue(result.contains(student.getStudentId()));
        assertTrue(result.contains("John Doe"));
        assertTrue(result.contains("MALE"));
    }
}
